In [3]:
import pandas as pd

# Read the CSV file
csv_file_path = r'C:\Users\srip1\OneDrive\Desktop\guvi\project_1\redbus_all_red.csv'
df = pd.read_csv(csv_file_path)

# Print the columns to debug
print("Columns in DataFrame:", df.columns)

# Ensure correct column names and drop unnecessary columns
df = df.rename(columns=lambda x: x.strip())  # Remove leading/trailing whitespaces

# Rename columns to match expected names
df.rename(columns={
    'Bus_name': 'Bus_Name',
    'Bus Type': 'Bus_Type',
    'Departure Time': 'Departure_Time',
    'Arrival Time': 'Arrival_Time',
    'Seat_Availability': 'Seat_Availability',
    'Bus Link': 'Bus_Link',
    'Bus Route': 'Bus_Route'
}, inplace=True)

# Format the DataFrame columns
try:
    if 'Departure_Time' in df.columns:
        df['Departure_Time'] = pd.to_datetime(df['Departure_Time'], format='%H:%M', errors='coerce').dt.time
    if 'Arrival_Time' in df.columns:
        df['Arrival_Time'] = pd.to_datetime(df['Arrival_Time'], format='%H:%M', errors='coerce').dt.time
except Exception as e:
    print(f"Error parsing date columns: {e}")

# Clean 'Seat_Availability' column and handle NaN values
if 'Seat_Availability' in df.columns:
    df['Seat_Availability'] = df['Seat_Availability'].astype(str).str.extract(r'(\d+)').fillna(0).astype(int)
else:
    print("Warning: 'Seat_Availability' column not found")

# Ensure 'Rating' and 'Fare' columns are properly formatted
if 'Rating' in df.columns:
    df['Rating'] = pd.to_numeric(df['Rating'], errors='coerce').fillna(0)  # Convert to float and fill NaNs with 0
if 'Fare' in df.columns:
    df['Fare'] = pd.to_numeric(df['Fare'], errors='coerce').fillna(0)  # Convert to float and fill NaNs with 0

# Ensure 'Bus_Name' column is present and treated as string
if 'Bus_Name' in df.columns:
    df['Bus_Name'] = df['Bus_Name'].astype(str).fillna('Unknown')
else:
    print("Warning: 'Bus_Name' column not found")

# Replace spaces with underscores in column names
df.columns = df.columns.str.replace(' ', '_')

# Save the cleaned DataFrame to a new CSV or use it directly
df.to_csv(r'C:\Users\srip1\OneDrive\Desktop\guvi\project_1\cleaned_redbus.csv', index=False)

print("Data preparation complete.")

Columns in DataFrame: Index(['Bus_name', 'Bus Type', 'Departure Time', 'Arrival Time', 'Duration',
       'Fare', 'Rating', 'Seat_Availability', 'Bus Link', 'Bus Route'],
      dtype='object')
Data preparation complete.

In [2]:
import pandas as pd

def load_csv(csv_file_path):
    # Read the CSV file
    df = pd.read_csv(csv_file_path)
    # Print the columns to debug
    print("Columns in DataFrame:", df.columns)
    return df

# Example usage
csv_file_path = r'C:\Users\srip1\OneDrive\Desktop\guvi\project 1\redbus_all_red.csv'
df = load_csv(csv_file_path)

Columns in DataFrame: Index(['Bus_name', 'Bus Type', 'Departure Time', 'Arrival Time', 'Duration',
       'Fare', 'Rating', 'Seat_Availability', 'Bus Link', 'Bus Route'],
      dtype='object')

In [3]:
def clean_column_names(df):
    # Remove leading/trailing whitespaces
    df = df.rename(columns=lambda x: x.strip())
    # Rename columns to match expected names
    df.rename(columns={
        'Bus_name': 'Bus_Name',
        'Bus Type': 'Bus_Type',
        'Departure Time': 'Departure_Time',
        'Arrival Time': 'Arrival_Time',
        'Seat_Availability': 'Seat_Availability',
        'Bus Link': 'Bus_Link',
        'Bus Route': 'Bus_Route'
    }, inplace=True)
    return df

# Example usage
df = clean_column_names(df)

In [4]:
import numpy as np

def format_columns(df):
    try:
        if 'Departure_Time' in df.columns:
            df['Departure_Time'] = pd.to_datetime(df['Departure_Time'], format='%H:%M', errors='coerce').dt.time
        if 'Arrival_Time' in df.columns:
            df['Arrival_Time'] = pd.to_datetime(df['Arrival_Time'], format='%H:%M', errors='coerce').dt.time
    except Exception as e:
        print(f"Error parsing date columns: {e}")

    if 'Seat_Availability' in df.columns:
        df['Seat_Availability'] = df['Seat_Availability'].astype(str).str.extract(r'(\d+)').fillna(0).astype(int)

    if 'Rating' in df.columns:
        df['Rating'] = pd.to_numeric(df['Rating'], errors='coerce').fillna(0)  # Convert to float and fill NaNs with 0
    
    if 'Fare' in df.columns:
        df['Fare'] = pd.to_numeric(df['Fare'], errors='coerce').fillna(0)  # Convert to float and fill NaNs with 0

    if 'Bus_Name' in df.columns:
        df['Bus_Name'] = df['Bus_Name'].astype(str).fillna('Unknown')
    
    return df

# Example usage
df = format_columns(df)

In [5]:
def handle_missing_values(df):
    df = df.replace({np.nan: None})
    return df

# Example usage
df = handle_missing_values(df)

In [6]:
def save_cleaned_csv(df, cleaned_csv_file_path):
    df.to_csv(cleaned_csv_file_path, index=False)
    print(f"Cleaned data saved to {cleaned_csv_file_path}")

# Example usage
cleaned_csv_file_path = r'C:\Users\srip1\OneDrive\Desktop\guvi\project 1\cleaned_redbus.csv'
save_cleaned_csv(df, cleaned_csv_file_path)

Cleaned data saved to C:\Users\srip1\OneDrive\Desktop\guvi\project 1\cleaned_redbus.csv

In [7]:
def main():
    csv_file_path = r'C:\Users\srip1\OneDrive\Desktop\guvi\project 1\redbus_all_red.csv'
    cleaned_csv_file_path = r'C:\Users\srip1\OneDrive\Desktop\guvi\project 1\cleaned_redbus.csv'

    # Load the CSV
    df = load_csv(csv_file_path)
    
    # Clean and format the DataFrame
    df = clean_column_names(df)
    df = format_columns(df)
    df = handle_missing_values(df)
    
    # Save the cleaned DataFrame
    save_cleaned_csv(df, cleaned_csv_file_path)

if __name__ == '__main__':
    main()

Columns in DataFrame: Index(['Bus_name', 'Bus Type', 'Departure Time', 'Arrival Time', 'Duration',
       'Fare', 'Rating', 'Seat_Availability', 'Bus Link', 'Bus Route'],
      dtype='object')
Cleaned data saved to C:\Users\srip1\OneDrive\Desktop\guvi\project 1\cleaned_redbus.csv

In [8]:
df

,Bus_Name,Bus_Type,Departure_Time,Arrival_Time,Duration,Fare,Rating,Seat_Availability,Bus_Link,Bus_Route
0,Kadamba Transport Corporation Limited (KTCL) -...,Non AC Seater 2+2,19:00:00,05:00:00,10h 00m,600.0,4.2,25,https://www.redbus.in/bus-tickets/pune-to-goa,Pune to Goa
1,Atmaram Gobus,VE A/C Sleeper (2+1),21:00:00,07:30:00,10h 30m,999.0,4.6,1,https://www.redbus.in/bus-tickets/pune-to-goa,Pune to Goa
2,Ashray Travels,Bharat Benz A/C Sleeper (2+1),21:00:00,08:30:00,11h 30m,950.0,4.5,11,https://www.redbus.in/bus-tickets/pune-to-goa,Pune to Goa
3,Ashray Amrutyog,A/C Sleeper (2+1),22:00:00,08:00:00,10h 00m,799.0,4.4,13,https://www.redbus.in/bus-tickets/pune-to-goa,Pune to Goa
4,IntrCity SmartBus,AC Sleeper (2+1),23:50:00,10:00:00,10h 10m,676.0,4.5,14,https://www.redbus.in/bus-tickets/pune-to-goa,Pune to Goa
...,...,...,...,...,...,...,...,...,...,...
835,City Land Travels,Volvo A/C Semi Sleeper (2+2),19:30:00,01:30:00,06h 00m,656.0,3.5,11,https://www.redbus.in/bus-tickets/palampur-to-...,Palampur to Chandigarh
836,New Himalaya Travels,Volvo A/C Semi Sleeper (2+2),19:35:00,01:30:00,05h 55m,720.0,4.8,8,https://www.redbus.in/bus-tickets/palampur-to-...,Palampur to Chandigarh
837,Laxmi holidays,None,None,None,None,0.0,0.0,0,https://www.redbus.in/bus-tickets/palampur-to-...,Palampur to Chandigarh
838,nan,None,None,None,None,0.0,0.0,0,https://www.redbus.in/bus-tickets/palampur-to-...,Palampur to Chandigarh
839,nan,None,None,None,None,0.0,0.0,0,https://www.redbus.in/bus-tickets/palampur-to-...,Palampur to Chandigarh

In [9]:
import pandas as pd
import pymysql

# Establish connection to MySQL
myconnection = pymysql.connect(host='localhost', user='root', passwd='root', database='swathi')

# Read the CSV file
csv_file_path = r'C:\Users\srip1\OneDrive\Desktop\guvi\project 1\redbus_all_red.csv'
df = pd.read_csv(csv_file_path)

# Remove leading/trailing whitespaces in column names
df = df.rename(columns=lambda x: x.strip())

# Rename columns to match expected names
df.rename(columns={
    'Bus_name': 'Bus_Name',
    'Bus Type': 'Bus_Type',
    'Departure Time': 'Departure_Time',
    'Arrival Time': 'Arrival_Time',
    'Seat_Availability': 'Seat_Availability',
    'Bus Link': 'Bus_Link',
    'Bus Route': 'Bus_Route'
}, inplace=True)

# Ensure 'Departure_Time' and 'Arrival_Time' are parsed as time
try:
    if 'Departure_Time' in df.columns:
        df['Departure_Time'] = pd.to_datetime(df['Departure_Time'], format='%H:%M', errors='coerce').dt.time
    if 'Arrival_Time' in df.columns:
        df['Arrival_Time'] = pd.to_datetime(df['Arrival_Time'], format='%H:%M', errors='coerce').dt.time
except Exception as e:
    print(f"Error parsing time columns: {e}")

# Clean 'Seat_Availability' column and handle NaN values
if 'Seat_Availability' in df.columns:
    df['Seat_Availability'] = df['Seat_Availability'].astype(str).str.extract(r'(\d+)').fillna(0).astype(int)

# Convert 'Rating' and 'Fare' to numeric, handling NaN values
if 'Rating' in df.columns:
    df['Rating'] = pd.to_numeric(df['Rating'], errors='coerce').fillna(0)
if 'Fare' in df.columns:
    df['Fare'] = pd.to_numeric(df['Fare'], errors='coerce').fillna(0)

# Treat 'Bus_Name' as string and fill NaN values
if 'Bus_Name' in df.columns:
    df['Bus_Name'] = df['Bus_Name'].astype(str).fillna('Unknown')

# Map pandas dtypes to MySQL dtypes
dtype_mapping = {
    'object': 'TEXT',
    'int64': 'INT',
    'int32': 'INT',
    'float64': 'FLOAT',
    'datetime64[ns]': 'DATETIME',
    'datetime.time': 'TIME'
}

# Replace spaces in column names with underscores for MySQL compatibility
df.columns = df.columns.str.replace(' ', '_')

# Generate the formatted string for creating the table with escaped column names and types
column_definitions = [f"`{col}` {dtype_mapping.get(str(df[col].dtype), 'TEXT')}" for col in df.columns]
table_definition = ", ".join(column_definitions)

# Define the table name
table_name = "redbus"

# Create cursor object
cursor = myconnection.cursor()

# Drop table if it exists (optional)
cursor.execute(f"DROP TABLE IF EXISTS {table_name}")

# Create table
create_table_query = f"CREATE TABLE {table_name} ({table_definition})"
print("Create Table Query:", create_table_query)  # Print the query to debug
cursor.execute(create_table_query)

# Commit the changes
myconnection.commit()

# Close the cursor and connection
cursor.close()
myconnection.close()

Create Table Query: CREATE TABLE redbus (`Bus_Name` TEXT, `Bus_Type` TEXT, `Departure_Time` TEXT, `Arrival_Time` TEXT, `Duration` TEXT, `Fare` FLOAT, `Rating` FLOAT, `Seat_Availability` INT, `Bus_Link` TEXT, `Bus_Route` TEXT)

In [10]:
df

,Bus_Name,Bus_Type,Departure_Time,Arrival_Time,Duration,Fare,Rating,Seat_Availability,Bus_Link,Bus_Route
0,Kadamba Transport Corporation Limited (KTCL) -...,Non AC Seater 2+2,19:00:00,05:00:00,10h 00m,600.0,4.2,25,https://www.redbus.in/bus-tickets/pune-to-goa,Pune to Goa
1,Atmaram Gobus,VE A/C Sleeper (2+1),21:00:00,07:30:00,10h 30m,999.0,4.6,1,https://www.redbus.in/bus-tickets/pune-to-goa,Pune to Goa
2,Ashray Travels,Bharat Benz A/C Sleeper (2+1),21:00:00,08:30:00,11h 30m,950.0,4.5,11,https://www.redbus.in/bus-tickets/pune-to-goa,Pune to Goa
3,Ashray Amrutyog,A/C Sleeper (2+1),22:00:00,08:00:00,10h 00m,799.0,4.4,13,https://www.redbus.in/bus-tickets/pune-to-goa,Pune to Goa
4,IntrCity SmartBus,AC Sleeper (2+1),23:50:00,10:00:00,10h 10m,676.0,4.5,14,https://www.redbus.in/bus-tickets/pune-to-goa,Pune to Goa
...,...,...,...,...,...,...,...,...,...,...
835,City Land Travels,Volvo A/C Semi Sleeper (2+2),19:30:00,01:30:00,06h 00m,656.0,3.5,11,https://www.redbus.in/bus-tickets/palampur-to-...,Palampur to Chandigarh
836,New Himalaya Travels,Volvo A/C Semi Sleeper (2+2),19:35:00,01:30:00,05h 55m,720.0,4.8,8,https://www.redbus.in/bus-tickets/palampur-to-...,Palampur to Chandigarh
837,Laxmi holidays,NaN,NaT,NaT,NaN,0.0,0.0,0,https://www.redbus.in/bus-tickets/palampur-to-...,Palampur to Chandigarh
838,nan,NaN,NaT,NaT,NaN,0.0,0.0,0,https://www.redbus.in/bus-tickets/palampur-to-...,Palampur to Chandigarh
839,nan,NaN,NaT,NaT,NaN,0.0,0.0,0,https://www.redbus.in/bus-tickets/palampur-to-...,Palampur to Chandigarh